### ISSUE TITLE
Bug: method AllEdges.get does not terminate

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon-graph#11]
I gave static code analysis a try and it found this bug:
The method `AllEdges.get(i)` does not terminate for `i > 0`

```java
package org.mastodon;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;
import org.mastodon.graph.Edge;
import org.mastodon.graph.ref.AbstractEdge;
import org.mastodon.mamut.model.ModelGraph;
import org.mastodon.mamut.model.Spot;

public class TestAllEdgesGet
{

	/**
	 * Currently broken unit test. There is an infinite loop
	 * in {@link org.mastodon.graph.ref.AllEdges#get(int, AbstractEdge)}
	 */
	@Test(timeout = 500)
	public void test() {
		ModelGraph graph = new ModelGraph();
		Spot a = graph.addVertex().init( 0, new double[ 3 ], 1 );
		Spot b = graph.addVertex().init( 1, new double[ 3 ], 1 );
		Spot c = graph.addVertex().init( 2, new double[ 3 ], 1 );
		graph.addEdge( a, b );
		graph.addEdge( a, c );
		Edge e = a.edges().get( 1 );
		assertNotNull( e );
	}
}
```

**Comment by tpietzsch** [comment]
That's cool! What tool do you use for static analysis?

**Comment by tpietzsch** [comment]
https://github.com/mastodon-sc/mastodon-graph/pull/12 fixes this particular problem.

In general, looking at that code again, it makes me feel slightly queasy that the `Edges` methods don't do any safety checks. Maybe that should be added? At least as an option for debugging (like [here](https://github.com/mastodon-sc/mastodon-collection/blob/87a50d38571b1e1d1732e41a2d9da4a932f2ab4d/src/main/java/org/mastodon/Options.java#L41))

**Comment by maarzt** [comment]
I would appreciate the safety checks.  Using -1 as "no entry value" and at the same time having `Pool.getObject(-1, ...)` return an object with undefined behavior feels like a recipe for evil things to happen. :smiling_imp: 

It's not the first time, that look at a bug where mastodon hangs, and an ref object with index -1 is involved.

**Comment by maarzt** [comment]
Oh sorry, the answer is:

**IntelliJ** :partying_face:
